spring:
  application:
    name: learn-redis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_redis?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: ww34079822
  redis:
    host: 127.0.0.1
    port: 6379